name: Setup Branch Protection

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name (owner/repo)'
        required: true
        default: 'vishwarajapathi/hdfc-pdf-converter'
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main'

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = '${{ github.event.inputs.branch }}';
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch,
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'test',
                    'docker-test'
                  ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              
              console.log(`✅ Branch protection enabled for ${branch}`);
            } catch (error) {
              console.error('❌ Failed to setup branch protection:', error);
              throw error;
            }
